name = "PihVfi890"
uuid = "dd4eb38f-f30a-455c-82d1-cdb2f11a43ae"
authors = ["mariyas24 <mariyas24@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
