name = "PihVfi890"
uuid = "dd4eb38f-f30a-455c-82d1-cdb2f11a43ae"
authors = ["mariyas24 <mariyas24@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
UtilityFunctions890 = "e0cbf102-630e-4f12-82cc-27e04986fe05"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
